### ISSUE TITLE
Fallback does not work for `language-fallback` plugin

### ISSUE THREAD

**Issue by obstschale** [2ndkauboy/language-fallback#4]
If multiple fallback locales are added to the array using `fallback_locale` filter, the new added locales are not available / used for this plugin.

I couldn't find out how to fix that :confused:

**Comment by 2ndkauboy** [comment]
Do you mean that they are not being downloaded? That is true. The download only happens through the settings form. Downloading a mofile while rendering the page would be a pretty bad idea.

**Comment by obstschale** [comment]
No, I don't mean the downloading. For my PR I checked the variables' values and saw that your plugin firstly checks itself, then the beta tester plugin, then twentyfifteen, etc.

But my custom fallback array, which I added using your filter, is only applied to after your plugin checks for fallbacks. So Language Fallback checks for one fallback (the one from your setting), but all other themes / plugins are checked for other fallbacks, which I added to the array.
